# Generated by Django 4.1.4 on 2022-12-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rgb', models.CharField(max_length=20)),
                ('is_trans', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('element_id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_num', models.CharField(max_length=20)),
                ('color_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('set_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMinifigs',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fig_num', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryParts',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_num', models.CharField(max_length=20)),
                ('color_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_spare', models.BooleanField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InventorySets',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_num', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minifig',
            fields=[
                ('fig_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('num_parts', models.IntegerField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('part_cat_id', models.IntegerField()),
                ('part_material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartsCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartsRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(max_length=10)),
                ('child_part_num', models.CharField(max_length=20)),
                ('parent_part_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('theme_id', models.IntegerField()),
                ('num_parts', models.IntegerField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
