# Generated by Django 4.1.4 on 2022-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryminifigs',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventoryparts',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventorysets',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryminifigs',
            name='inventory_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryparts',
            name='inventory_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorysets',
            name='inventory_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partsrelationship',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
