# Generated by Django 4.1.4 on 2022-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0002_inventoryminifigs_id_inventoryparts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
