# Generated by Django 4.1.4 on 2022-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0003_alter_theme_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsrelationship',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
