services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: missabrick
      POSTGRES_PASSWORD: missabrick
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webapp:
    build: .
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:80"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  cache:
  postgres-data:
