version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/opt/app/static

  webapp:
    build: .
    env_file: .env

  worker:
    build: .
    command: celery -A make_celery worker --loglevel INFO
    env_file: .env

  flower:
    build: .
    command: celery -A make_celery flower
    env_file: .env
    ports:
      - "5555:5555"

volumes:
  cache:
    driver: local
