version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/opt/app/static

  webapp:
    build: .
    env_file: .env

  worker:
    build: .
    command: celery -A make_celery worker --loglevel INFO -B
    env_file: .env

  flower:
    build: .
    command: celery -A make_celery flower
    env_file: .env
    ports:
      - "5555:5555"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: missabrick
      POSTGRES_PASSWORD: missabrick
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  cache:
    driver: local
  postgres-data:
    driver: local
