"""Initial Migration

Revision ID: 6c118d59d498
Revises:
Create Date: 2023-06-15 17:19:10.974002

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c118d59d498"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "color",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rgb", sa.String(length=20), nullable=False),
        sa.Column("is_trans", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "part_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "theme",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["theme.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column(
            "email",
            sqlalchemy_utils.types.email.EmailType(length=255),
            nullable=False,
        ),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(max_length=1137),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "year",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generic_set",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("num_parts", sa.Integer(), nullable=False),
        sa.Column("img_url", sa.Text(), nullable=False),
        sa.Column("is_minifig", sa.Boolean(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column("year_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme.id"],
        ),
        sa.ForeignKeyConstraint(
            ["year_id"],
            ["year.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "part",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("material", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["part_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "element",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.String(length=20), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generic_set_part",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("is_spare", sa.Boolean(), nullable=False),
        sa.Column("img_url", sa.Text(), nullable=False),
        sa.Column("set_id", sa.String(), nullable=False),
        sa.Column("part_id", sa.String(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["generic_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generic_set_rel",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.Column("child_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["generic_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["generic_set.id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generic_set_rel")
    op.drop_table("generic_set_part")
    op.drop_table("element")
    op.drop_table("part")
    op.drop_table("generic_set")
    op.drop_table("year")
    op.drop_table("user")
    op.drop_table("theme")
    op.drop_table("part_category")
    op.drop_table("color")
    # ### end Alembic commands ###
