# Generated by Django 4.1.4 on 2022-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0004_alter_partsrelationship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryminifigs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryparts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorysets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
