# Generated by Django 4.1.4 on 2022-12-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0005_alter_inventoryminifigs_id_alter_inventoryparts_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='part_num',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='set_num',
        ),
        migrations.RemoveField(
            model_name='inventoryminifigs',
            name='fig_num',
        ),
        migrations.RemoveField(
            model_name='inventoryminifigs',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventoryparts',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='inventoryparts',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventoryparts',
            name='part_num',
        ),
        migrations.RemoveField(
            model_name='inventorysets',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventorysets',
            name='set_num',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_cat_id',
        ),
        migrations.RemoveField(
            model_name='partsrelationship',
            name='child_part_num',
        ),
        migrations.RemoveField(
            model_name='partsrelationship',
            name='parent_part_num',
        ),
        migrations.RemoveField(
            model_name='set',
            name='theme_id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.set'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_minifig',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='minifig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.minifig'),
        ),
        migrations.AddField(
            model_name='inventoryminifigs',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryminifigs',
            name='minifig',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.minifig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryparts',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryparts',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryparts',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorysets',
            name='_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorysets',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.partscategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsrelationship',
            name='child_part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='legoapp.part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsrelationship',
            name='parent_part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='legoapp.part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.theme'),
        ),
    ]
