# Generated by Django 4.1.4 on 2022-12-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0006_remove_element_color_id_remove_element_part_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.part'),
        ),
    ]
