# Generated by Django 4.1.4 on 2022-12-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legoapp', '0007_alter_element_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryminifigs',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryparts',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
        ),
        migrations.AlterField(
            model_name='inventorysets',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legoapp.inventory'),
        ),
    ]
